version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=solid
      - POSTGRES_DB=solid
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: solid
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local